parameters:
    - name: agent
      type: string
      default: windows-latest
    - name: preTestSteps
      type: stepList
      default:
        - template: ../task/download-pipeline-artifact-task.yml
    - name: afterTestSteps
      type: stepList
      default:
        - template: ../task/publish-test-results-task.yml
  
jobs:
    - job: ARMTTK
      displayName: 'Check ARM template with TTK'
      pool:
        vmImage: ${{ parameters.agent }}
      steps:
        - ${{ parameters.preTestSteps }}
        - template: ../task/arm-ttk-checker-task.yml
        - ${{ parameters.afterTestSteps }}